import { Inter } from "next/font/google";
import "./globals.css";
import "./Loader.css";
const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from "./AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
