# Generated by Django 4.2.14 on 2024-07-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='/imgs/background2.jpg', null=True, upload_to='img'),
        ),
    ]
