# Generated by Django 4.2.14 on 2024-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='/images/background2.jpg', null=True, upload_to='img'),
        ),
    ]
