# Generated by Django 4.2.14 on 2024-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
