# Generated by Django 4.2.14 on 2024-07-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0005_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='verified',
        ),
    ]
