# Generated by Django 4.2.14 on 2024-07-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0006_remove_project_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
