# Generated by Django 4.2.14 on 2024-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0008_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://github.com/ousamuel/cashtrack', unique=True),
            preserve_default=False,
        ),
    ]
