# Generated by Django 4.2.14 on 2024-07-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0009_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
    ]
