# Generated by Django 4.2.14 on 2024-07-17 01:09

from django.db import migrations, models
import myProject.models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0010_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(default='user', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[myProject.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
