# Generated by Django 4.2.14 on 2024-07-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0014_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='test123'),
            preserve_default=False,
        ),
    ]
