# Generated by Django 4.2.14 on 2024-07-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0015_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
