# Generated by Django 4.2.14 on 2024-07-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0017_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
