# Generated by Django 4.2.14 on 2024-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0019_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
