# Generated by Django 4.2.14 on 2024-07-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0021_remove_project_user_id_project_creator_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_id',
        ),
    ]
