# Generated by Django 4.2.14 on 2024-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0025_remove_project_user_project_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
