name: Deploy react-django/backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key
        chmod 600 key
        eval "$(ssh-agent -s)"
        ssh-add key
      shell: bash

    - name: Create directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /home/${{ secrets.EC2_USER }}/react-django/backend"

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/react-django/backend

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
        cd /home/${{ secrets.EC2_USER }}/react-django/backend
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        EOF

    - name: Migrate database and collect static files
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
        cd /home/${{ secrets.EC2_USER }}/react-django/backend
        source venv/bin/activate
        python manage.py migrate
        python manage.py collectstatic --noinput
        EOF

    - name: Restart Gunicorn
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
        sudo systemctl restart gunicorn
        EOF
