name: Deploy Django Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key
        chmod 600 key
        eval "$(ssh-agent -s)"
        ssh-add key
      shell: bash

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/your-repo/backend
      shell: bash

    - name: Install dependencies and run migrations
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
        cd /home/${{ secrets.EC2_USER }}/your-repo/backend
        source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
        pip
