name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /var/www/React-Django
        git pull origin main
        python3 -m venv venv
        pip install -r requirements.txt
        sudo systemctl daemon-reload
        sudo systemctl start gunicorn
        sudo systemctl restart gunicorn
        EOF
      shell: bash
