name: Deploy Django Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        eval "$(ssh-agent -s)"
        ssh-add key.pem
      shell: bash

    - name: Copy files to EC2
      run: |
        scp -i ${{EC2_SSH_KEY}} . ec2-user@ip-172-31-31-33.us-east-2.compute.internal:/home/ec2-user/React-Django/backend
      shell: bash

    - name: Install dependencies and run migrations
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/${{ secrets.EC2_USER }}/React-Django/backend
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        sudo systemctl restart gunicorn
        EOF
      shell: bash
